services:
  catshi-api:
    container_name: "catshi-api"
    build:
      context: .
      dockerfile: api/Dockerfile
    init: true
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=sqlite:/app/db/catshi.sqlite?mode=rwc

  catshi-bot:
    container_name: "catshi-bot"
    build:
      context: .
      dockerfile: bot/Dockerfile
    init: true
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=sqlite:/app/db/catshi.sqlite?mode=rwc
      - GUILD_ID=${GUILD_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}

  migrate:
    container_name: "catshi-migrate"
    build:
      context: .
      dockerfile: Dockerfile.migrate
