services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    init: true
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_PORT=${API_PORT}
      - DATABASE_URL=sqlite:/app/db/catshi.sqlite?mode=rwc

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    init: true
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=sqlite:/app/db/catshi.sqlite?mode=rwc
      - GUILD_ID=${GUILD_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
