services:
  catshi-api:
    build:
      target: prod
    restart: unless-stopped
    volumes:
      - ${PROD_SQLITE_DIR}:/app/db

  catshi-bot:
    build:
      target: prod
    restart: unless-stopped
    volumes:
      - ${PROD_SQLITE_DIR}:/app/db

  catshi-migrate:
    # No PSQL in prod yet - just turn off this service.
    entrypoint: ["true"]
