services:
  api:
    build:
      target: prod
    restart: unless-stopped
    volumes:
      - ${PROD_SQLITE_PATH}:/app/catshi.sqlite

  bot:
    build:
      target: prod
    restart: unless-stopped
    volumes:
      - ${PROD_SQLITE_PATH}:/app/catshi.sqlite
