CREATE TABLE orders (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    direction TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    shares_price INTEGER NOT NULL,
    fees INTEGER NOT NULL,
    cost_basis INTEGER NOT NULL,
    instrument_id INTEGER REFERENCES instruments(id) NOT NULL,
    owner_id INTEGER REFERENCES users(id) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);